update OoyalaSkinSampleApp and ExoSampleApp to use updated react libraries
still see crash:
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                  Process: com.ooyala.sample.SkinCompleteSampleApp, PID: 29801
                  java.lang.RuntimeException: An error occurred while executing doInBackground()
                      at android.os.AsyncTask$3.done(AsyncTask.java:309)
                      at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                      at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                      at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                      at java.lang.Thread.run(Thread.java:818)
                   Caused by: java.lang.NoClassDefFoundError: com.facebook.react.CoreModulesPackage$1
                      at com.facebook.react.CoreModulesPackage.getNativeModules(CoreModulesPackage.java:66)
                      at com.facebook.react.LazyReactPackage.createNativeModules(LazyReactPackage.java:39)
                      at com.facebook.react.XReactInstanceManagerImpl.processPackage(XReactInstanceManagerImpl.java:932)
                      at com.facebook.react.XReactInstanceManagerImpl.createReactContext(XReactInstanceManagerImpl.java:842)
                      at com.facebook.react.XReactInstanceManagerImpl.access$600(XReactInstanceManagerImpl.java:103)
                      at com.facebook.react.XReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(XReactInstanceManagerImpl.java:203)
                      at com.facebook.react.XReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(XReactInstanceManagerImpl.java:182)
                      at android.os.AsyncTask$2.call(AsyncTask.java:295)
                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                      at java.lang.Thread.run(Thread.java:818) 